# increase priority
config_priority: 107
config_change_watcher_enabled: false
# change to 5 seconds
config_polling_duration: "PT10S"

server:
    host: "0.0.0.0"
    port: 8026

# Requires defined order
providers:
    - type: "yaml-type"
      config:
          enabled: true
          message: "yaml-hi"
    - class: "yaml-fqcn"
      optional: true

